# dockerfile_template_2

# Application top directory
ARG APP_TOP=/root/Tpg
# Add ipmitool to the image
RUN yum -y update && yum install -y ipmitool && yum clean all -y
# Set some EPICS env vars
ENV BASE_MODULE_VERSION R3.15.5-1.1
# Prepare the build directory
RUN mkdir -p ${APP_TOP}
WORKDIR ${APP_TOP}
# Copy files from the repo.
ADD Tpg .
ADD scripts/start_ioc.sh .
ADD config config
# Build the application
RUN make distclean && make
# Copy the data
COPY data.zip .
# For example if APP_TOP=/whatever then /whatever/data/ contains sioc-smurf-ts01/.
RUN unzip data.zip -d data
RUN rm data.zip

# Create the final image
FROM centos:6.10
# Remember ARG and ENV not persist after FROM.
ARG APP_TOP=/root/Tpg
ENV EPICS_CA_REPEATER_PORT 5065
ENV EPICS_CA_AUTO_ADDR_LIST YES
ENV EPICS_CA_SERVER_PORT 5064
# For example, if IOC_DATA=/whatever/data/, then /whatever/data/sioc-smrf-ts01/ contains autosave/, etc.
ENV IOC_DATA $APP_TOP/ioc_data
# Copy the IOC produced during the building stage
COPY --from=builder $APP_TOP $APP_TOP
# Copy the ipmitool binary
COPY --from=builder /usr/bin/ipmitool /usr/bin/ipmitool
# Go to the application top level
WORKDIR $APP_TOP
# Start the IOC using the default shelfmanager name and slot number
ENTRYPOINT ["./start_ioc.sh","-S", "shm-smrf-sp01", "-N", "2"]
